### ISSUE TITLE
Why did you close my PRs with no comments?

### ISSUE THREAD

**Issue by dermers** [bacigaluped/assignment1#14]
You closed my PRs but did not explain why whatsoever. It has been up since Sunday. 
It would be appreciated if you could merge my PRs because y'all are the only spec team we got that did not accept our String and Object standardization. This prevents us from making our assignment compile-able.

**Comment by bacigaluped** [comment]
We had to completely remove the string file for git which required a history rewrite and closed your PRs. We're using the student standardization for the string and object classes now.
