### ISSUE TITLE
PRs and Documenting changes

### ISSUE THREAD

**Issue by chasebish** [bacigaluped/assignment1#17]
Hey guys,

I see you keep pushing some changes to the repo. It would be very helpful to the groups that are relying on your API if you can detail the changes you make. Additionally, the quicker you respond to our issues and PRs the better, because we can make changes to them for you so we can make sure it all works well with our implementation.

**Comment by bacigaluped** [comment]
Understood, we struggled early in the assignment with git since we had a string implementation and needed to rewrite the git history which closed the open PRs. We'll be more communicative going forward.
