### ISSUE TITLE
Should this be 3?

### ISSUE THREAD

**Issue by spencerlachance** [bacigaluped/assignment1#21]
https://github.com/bacigaluped/assignment1/blob/e049addd77e92ae5963fe59d65654e77a658cf65/test-map.cpp#L30

**Comment by bacigaluped** [comment]
No because the key already exists in the map.

The map before the put on line 29:
{
  ["key", "val"], ["key2", "val"]
}

The map after the put:
{
  ["key", "new val"], ["key2", "val"]
}


Let me know that's causing you issues in your implementation.

**Comment by spencerlachance** [comment]
Oh yeah duh, that's my b
