### ISSUE TITLE
Map returns an Object, and then that Object checks to see if a String is equal

### ISSUE THREAD

**Issue by noelprince** [bacigaluped/assignment1#24]
On the test at line 29, you check to see if calling equal with a return Object against a String returns true. This only works if there are two maps which are completely separate for String->String vs Object->Object; otherwise, the return Object from the get has to be casted to a String for comparison, or the String value you are checking against needs to call equals on the return Object.

**Comment by bacigaluped** [comment]
I see what you're saying. Would you like me to change the assert statement to check that the hashes of the values are equal?

**Comment by noelprince** [comment]
If you just switch the order for any tests that do that, they will work. Thank you :)

**Comment by bacigaluped** [comment]
Before I push anything, would this suffice for this specific case?:

`String* new_string = new String("new val");
assert(new_string->equals(m->get(key)));`

**Comment by noelprince** [comment]
Yes that should work thank you. In class so might take time to respond from
now-
